/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#526478',
        background: '#fef9ed',
        'tertiary-fixed': '#ffdad4',
        'on-primary-fixed': '#0b2013',
        'on-error-container': '#93000a',
        'surface-container-low': '#f8f3e7',
        'on-primary-fixed-variant': '#364c3c',
        'on-surface': '#1d1c15',
        'surface-container': '#f2ede2',
        'on-tertiary-fixed-variant': '#80281b',
        'surface-variant': '#e7e2d6',
        'on-secondary-fixed': '#091d2e',
        'primary-fixed': '#d0e9d4',
        'primary-container': '#1b3022',
        'on-tertiary-fixed': '#400200',
        'outline-variant': '#c3c8c1',
        'primary-fixed-dim': '#b4cdb8',
        outline: '#737973',
        error: '#ba1a1a',
        'on-primary-container': '#819986',
        surface: '#fef9ed',
        'on-secondary-fixed-variant': '#36485b',
        'on-surface-variant': '#434843',
        'inverse-primary': '#b4cdb8',
        'secondary-fixed-dim': '#b5c8df',
        secondary: '#4e6073',
        'surface-container-highest': '#e7e2d6',
        'tertiary-container': '#5a0c04',
        'surface-bright': '#fef9ed',
        'on-tertiary-container': '#e3715f',
        'surface-dim': '#dedace',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        primary: '#061b0e',
        'inverse-surface': '#323029',
        'surface-container-high': '#ede8dc',
        tertiary: '#370100',
        'on-primary': '#ffffff',
        'on-background': '#1d1c15',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'secondary-fixed': '#d1e4fb',
        'surface-tint': '#4d6453',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f5f0e4',
        'tertiary-fixed-dim': '#ffb4a7',
        'secondary-container': '#cfe2f9',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
